### ISSUE TITLE
Commands to reproduce Table 2

### ISSUE THREAD

**Issue by sudipansaha** [dbp1994/bare-wacv-2023#2]
Can you please check whether following commands are correct for experiments corresponding to Table 2 in the paper, dataset MNIST, batch size 64:

**50% SYM**

python batch_rewgt.py --dataset mnist --noise_rate 0.5 --noise_type sym --loss_name cce --data_aug 0 --batch_size 64 --num_epoch 200 --num_runs 5

**45% CC**

python batch_rewgt.py --dataset mnist --noise_rate 0.45 --noise_type cc --loss_name cce --data_aug 0 --batch_size 64 --num_epoch 200 --num_runs 5

While for SYM, I am getting scores similar to (or slightly bettet than) that reported in the paper, for CC I am getting much lower score. I was wondering if the above-mentioned command needs to be modified?

**Comment by dbp1994** [comment]
Hi Sudipan,

For class-conditional label noise, what I suspect is the following: the empirical distributions for clean and noisily labelled data are not as well-separated as we typically get in symmetric label noise. So, I would suggest trying out a few different random initializers as that help find better 'initial separability'. I too faced this problem of getting lower averages and higher variances but using different random initializers helped a lot. Even something as silly as randomly initializing a network for 5-10 times in a for loop before using those initial weights can also work.
